source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'


target 'UploadPdfDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for UploadPdfDemo

pod 'AFNetworking', '~> 3.0'

end
